apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-2
  name: backend-2
  namespace: app
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend-2
  type: ClusterIP
